export const ActionTypes = {
    ON_USER_LOGIN : 'ON_USER_LOGIN',
    ON_USER_LOGIN_SUCCESS : 'ON_USER_LOGIN_SUCCESS',
    ON_USER_LOGIN_FAILURE : 'ON_USER_LOGIN_FAILURE',

    ON_POPULAR_MOVIE:'ON_POPULAR_MOVIE',
    ON_POPULAR_MOVIE_SUCCESS:'ON_POPULAR_MOVIE_SUCCESS',
    ON_POPULAR_MOVIE_FAILURE:'ON_POPULAR_MOVIE_FAILURE',
};
